/*
    This file is part of Nori, a simple educational ray tracer

    Copyright (c) 2015 by Wenzel Jakob

    Nori is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License Version 3
    as published by the Free Software Foundation.

    Nori is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program. If not, see <http://www.gnu.org/licenses/>.
*/

#include <nori/bitmap.h>
#include <ImfInputFile.h>
#include <ImfOutputFile.h>
#include <ImfChannelList.h>
#include <ImfStringAttribute.h>
#include <ImfVersion.h>
#include <ImfIO.h>

#include <memory>
#define STB_IMAGE_WRITE_IMPLEMENTATION
#include <stb_image_write.h>

NORI_NAMESPACE_BEGIN

Bitmap::Bitmap(const std::string &filename) {
    Imf::InputFile file(filename.c_str());
    const Imf::Header &header = file.header();
    const Imf::ChannelList &channels = header.channels();

    Imath::Box2i dw = file.header().dataWindow();
    resize(dw.max.y - dw.min.y + 1, dw.max.x - dw.min.x + 1);

    cout << "Reading a " << cols() << "x" << rows() << " OpenEXR file from \""
         << filename << "\"" << endl;

    const char *ch_r = nullptr, *ch_g = nullptr, *ch_b = nullptr;
    for (Imf::ChannelList::ConstIterator it = channels.begin(); it != channels.end(); ++it) {
        std::string name = toLower(it.name());

        if (it.channel().xSampling != 1 || it.channel().ySampling != 1) {
            /* Sub-sampled layers are not supported */
            continue;
        }

        if (!ch_r && (name == "r" || name == "red" || 
                endsWith(name, ".r") || endsWith(name, ".red"))) {
            ch_r = it.name();
        } else if (!ch_g && (name == "g" || name == "green" || 
                endsWith(name, ".g") || endsWith(name, ".green"))) {
            ch_g = it.name();
        } else if (!ch_b && (name == "b" || name == "blue" || 
                endsWith(name, ".b") || endsWith(name, ".blue"))) {
            ch_b = it.name();
        }
    }

    if (!ch_r || !ch_g || !ch_b)
        throw NoriException("This is not a standard RGB OpenEXR file!");

    size_t compStride = sizeof(float),
           pixelStride = 3 * compStride,
           rowStride = pixelStride * cols();

    char *ptr = reinterpret_cast<char *>(data());

    Imf::FrameBuffer frameBuffer;
    frameBuffer.insert(ch_r, Imf::Slice(Imf::FLOAT, ptr, pixelStride, rowStride)); ptr += compStride;
    frameBuffer.insert(ch_g, Imf::Slice(Imf::FLOAT, ptr, pixelStride, rowStride)); ptr += compStride;
    frameBuffer.insert(ch_b, Imf::Slice(Imf::FLOAT, ptr, pixelStride, rowStride)); 
    file.setFrameBuffer(frameBuffer);
    file.readPixels(dw.min.y, dw.max.y);

}

Bitmap::Bitmap(const std::string &filename,BitmapBoundaryType type):
    Bitmap(filename)
{
    m_bcu = type;
    m_bcv = type;
}

void Bitmap::save(const std::string &filename) {
    cout << "Writing a " << cols() << "x" << rows() 
         << " OpenEXR file to \"" << filename << "\"" << endl;

    Imf::Header header((int) cols(), (int) rows());
    header.insert("comments", Imf::StringAttribute("Generated by Nori"));

    Imf::ChannelList &channels = header.channels();
    channels.insert("R", Imf::Channel(Imf::FLOAT));
    channels.insert("G", Imf::Channel(Imf::FLOAT));
    channels.insert("B", Imf::Channel(Imf::FLOAT));

    Imf::FrameBuffer frameBuffer;
    size_t compStride = sizeof(float),
           pixelStride = 3 * compStride,
           rowStride = pixelStride * cols();

    char *ptr = reinterpret_cast<char *>(data());
    frameBuffer.insert("R", Imf::Slice(Imf::FLOAT, ptr, pixelStride, rowStride)); ptr += compStride;
    frameBuffer.insert("G", Imf::Slice(Imf::FLOAT, ptr, pixelStride, rowStride)); ptr += compStride;
    frameBuffer.insert("B", Imf::Slice(Imf::FLOAT, ptr, pixelStride, rowStride)); 

    Imf::OutputFile file(filename.c_str(), header);
    file.setFrameBuffer(frameBuffer);
    file.writePixels((int) rows());
}

static float GammaCorrect(float value) {
    if (value <= 0.0031308f) return 12.92f * value;
    return 1.055f * std::pow(value, 1.f/2.4f) - 0.055f;
}
static float Clamp(float val, float low, float high) {
    if (val < low)
        return low;
    else if (val > high)
        return high;
    else
        return val;
}

void Bitmap::saveToLDR(const std::string &filename) {
    cout << "Writing a " << cols() << "x" << rows()
    << " PNG file to \"" << filename << "\"" << endl;

    std::unique_ptr<uint8_t[]> rgb8(new uint8_t[3 * cols() * rows()]);
    uint8_t *dst = rgb8.get();
    for (int y = 0; y < rows(); ++y) {
        for (int x = 0; x < cols(); ++x) {
#define TO_BYTE(v) (uint8_t) Clamp(255.f * GammaCorrect(v) + 0.5f, 0.f, 255.f)
            dst[0] = TO_BYTE(coeff(y,x).r());
            dst[1] = TO_BYTE(coeff(y,x).g());
            dst[2] = TO_BYTE(coeff(y,x).b());
#undef TO_BYTE
            dst += 3;
        }
    }
    stbi_write_png(filename.c_str(),cols(),rows(),3,rgb8.get(),3*cols());
}

Color3f Bitmap::evalTexel(int row, int col) const{
        if (row < 0 || row >= rows()) {
            /* Encountered an out of bounds access -- determine what to do */
            switch (m_bcu) {
                case BitmapBoundaryType::EClamp:
                    // Clamp to the outermost sample position
                    row = clamp(row, 0, rows()- 1);
                    break;
                case BitmapBoundaryType::ERepeat:
                    row = row%rows();
                    break;
            }
        }

        if (col < 0 || col >= cols()) {
            /* Encountered an out of bounds access -- determine what to do */
            switch (m_bcv) {
                case BitmapBoundaryType::EClamp:
                    // Clamp to the outermost sample position
                    col = clamp(col, 0, cols() - 1);
                    break;
                case BitmapBoundaryType::ERepeat:
                    col = col%cols();
                    break;
            }
        }

        return (*this)(row,col);
}

void Bitmap::evalGradientBilinear(const Point2f &uv, Color3f *gradient) const {
    if ((!std::isfinite(uv.x()) || !std::isfinite(uv.y()))) {
        std::cerr<<("evalGradientBilinear(): encountered a NaN!\n");
        gradient[0] = gradient[1] = Color3f(0.0f);
        return;
    }

    /* Convert to fractional pixel coordinates on the specified level */
    float u = uv.x() * cols() - 0.5f, v = uv.y() * rows()- 0.5f;

    int xPos = floor(u), yPos = floor(v);
    float dx = u - xPos, dy = v - yPos;

    const Color3f p00 = evalTexel(yPos,   xPos);
    const Color3f p10 = evalTexel(yPos,   xPos+1);
    const Color3f p01 = evalTexel(yPos+1, xPos);
    const Color3f p11 = evalTexel(yPos+1, xPos+1);
    Color3f tmp = p01 + p10 - p11;

    gradient[0] = (p10 + p00*(dy-1) - tmp*dy) * static_cast<float> (cols());
    gradient[1] = (p01 + p00*(dx-1) - tmp*dx) * static_cast<float> (rows());
}

NORI_NAMESPACE_END
